export enum RoutePath {
  Action = '/action',
  Any = '*',
  Auth = '/auth',
  ChangeName = '/change-name',
  ChangePassword = '/change-password',
  ContactUs = '/contact-us',
  Create = '/create',
  CreateDetails = '/create/:id',
  CreateScene = '/create/scene',
  Fable = '/fables/:id',
  FableRead = '/fables/:id/read',
  Feedback = '/feedback',
  ForgotPassword = '/forgot-password',
  Index = '/',
  Notification = '/notification/:type',
  Plan = '/plan/:identifier/:action',
  Profile = '/profile',
  Request = '/request/:id',
  SignIn = '/sign-in',
  SignUp = '/sign-up',
  VerifyEmail = '/verify-email',
}
