export enum RoutePath {
  Any = '*',
  Auth = '/auth',
  Action = '/action',
  ForgotPassword = '/forgot-password',
  SignIn = '/sign-in',
  VerifyEmail = '/verify-email',
  ContactUs = '/contact-us',
  Create = '/create',
  CreateScene = '/create/scene',
  Fable = '/fables/:id',
  Feedback = '/feedback',
  Index = '/',
  Notification = '/notification/:type',
  Profile = '/profile',
  Request = '/request/:id',
  SignUp = '/sign-up',
}
