export enum RoutePath {
  Any = '*',
  Auth = '/auth',
  AuthAction = '/auth/action',
  AuthEmailVerification = '/auth/email-verification',
  AuthForgotPassword = '/auth/forgot-password',
  AuthSignIn = '/auth/sign-in',
  AuthSignUp = '/auth/sign-up',
  AuthVerifyEmail = '/auth/verify-email',
  ContactUs = '/contact-us',
  ContactUsSuccess = '/contact-us/success',
  Create = '/create',
  Fable = '/fables/:id',
  Feedback = '/feedback',
  Index = '/',
  Profile = '/profile',
  Request = '/request/:id',
}
