import {
  logoGoogle,
  add,
  arrowBack,
  personCircle,
  bookOutline,
  chevronForward,
  mailOutline,
  chatboxEllipsesOutline,
  logoApple,
  logoFacebook,
  lockClosedOutline,
  logOutOutline,
  documentTextOutline,
  helpBuoyOutline,
  closeOutline,
  arrowForwardOutline,
  personOutline,
} from 'ionicons/icons';

export const ICON = {
  add,
  apple: logoApple,
  'arrow-back': arrowBack,
  'arrow-forward-outline': arrowForwardOutline,
  'book-outline': bookOutline,
  'chatbox-ellipses-outline': chatboxEllipsesOutline,
  'chevron-forward': chevronForward,
  'close-outline': closeOutline,
  'document-text-outline': documentTextOutline,
  facebook: logoFacebook,
  google: logoGoogle,
  'help-buoy-outline': helpBuoyOutline,
  'lock-closed-outline': lockClosedOutline,
  'log-out-outline': logOutOutline,
  'mail-outline': mailOutline,
  'person-circle': personCircle,
  'person-outline': personOutline,
};
