// @ts-nocheck

/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Fabled API
 * Fabled API Documentation
 * OpenAPI spec version: 1.0
 */
import { useInfiniteQuery, useMutation, useQuery } from '@tanstack/react-query';

import { useCustomInstance } from '../hooks/useCustomInstance/index';

import type {
  InfiniteData,
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseInfiniteQueryOptions,
  UseInfiniteQueryResult,
  UseMutationOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';
import type {
  Bootstrap,
  GetBootstrapParams,
  GetStoriesParams,
  GetStoryParams,
  Stories,
  Story,
} from './client.schemas';

// eslint-disable-next-line
type SecondParameter<T extends (...args: any) => any> = T extends (
  config: any,
  args: infer P
) => any
  ? P
  : never;

/**
 * @summary Get app bootstrap data
 */
export const useGetBootstrapHook = () => {
  const getBootstrap = useCustomInstance<Bootstrap>();

  return (
    params?: GetBootstrapParams,
    options?: SecondParameter<ReturnType<typeof useCustomInstance>>,
    signal?: AbortSignal
  ) => {
    return getBootstrap(
      { method: 'get', params, signal, url: `/api/bootstrap` },
      options
    );
  };
};

export const getGetBootstrapQueryKey = (params?: GetBootstrapParams) => {
  return [`/api/bootstrap`, ...(params ? [params] : [])] as const;
};

export const useGetBootstrapInfiniteQueryOptions = <
  TData = InfiniteData<
    Awaited<ReturnType<ReturnType<typeof useGetBootstrapHook>>>,
    GetBootstrapParams['skip']
  >,
  TError = unknown,
>(
  params?: GetBootstrapParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<ReturnType<typeof useGetBootstrapHook>>>,
        TError,
        TData,
        Awaited<ReturnType<ReturnType<typeof useGetBootstrapHook>>>,
        QueryKey,
        GetBootstrapParams['skip']
      >
    >;
    request?: SecondParameter<ReturnType<typeof useCustomInstance>>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetBootstrapQueryKey(params);

  const getBootstrap = useGetBootstrapHook();

  const queryFn: QueryFunction<
    Awaited<ReturnType<ReturnType<typeof useGetBootstrapHook>>>,
    QueryKey,
    GetBootstrapParams['skip']
  > = ({ signal, pageParam }) =>
    getBootstrap({ skip: pageParam, ...params }, requestOptions, signal);

  return {
    cacheTime: 0,
    queryFn,
    queryKey,
    refetchOnWindowFocus: false,
    ...queryOptions,
  } as UseInfiniteQueryOptions<
    Awaited<ReturnType<ReturnType<typeof useGetBootstrapHook>>>,
    TError,
    TData,
    Awaited<ReturnType<ReturnType<typeof useGetBootstrapHook>>>,
    QueryKey,
    GetBootstrapParams['skip']
  > & { queryKey: QueryKey };
};

export type GetBootstrapInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof useGetBootstrapHook>>>
>;
export type GetBootstrapInfiniteQueryError = unknown;

/**
 * @summary Get app bootstrap data
 */
export const useGetBootstrapInfinite = <
  TData = InfiniteData<
    Awaited<ReturnType<ReturnType<typeof useGetBootstrapHook>>>,
    GetBootstrapParams['skip']
  >,
  TError = unknown,
>(
  params?: GetBootstrapParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<ReturnType<typeof useGetBootstrapHook>>>,
        TError,
        TData,
        Awaited<ReturnType<ReturnType<typeof useGetBootstrapHook>>>,
        QueryKey,
        GetBootstrapParams['skip']
      >
    >;
    request?: SecondParameter<ReturnType<typeof useCustomInstance>>;
  }
): UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = useGetBootstrapInfiniteQueryOptions(params, options);

  const query = useInfiniteQuery(queryOptions) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const useGetBootstrapQueryOptions = <
  TData = Awaited<ReturnType<ReturnType<typeof useGetBootstrapHook>>>,
  TError = unknown,
>(
  params?: GetBootstrapParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<ReturnType<typeof useGetBootstrapHook>>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<ReturnType<typeof useCustomInstance>>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetBootstrapQueryKey(params);

  const getBootstrap = useGetBootstrapHook();

  const queryFn: QueryFunction<
    Awaited<ReturnType<ReturnType<typeof useGetBootstrapHook>>>
  > = ({ signal }) => getBootstrap(params, requestOptions, signal);

  return {
    cacheTime: 0,
    queryFn,
    queryKey,
    refetchOnWindowFocus: false,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<ReturnType<typeof useGetBootstrapHook>>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetBootstrapQueryResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof useGetBootstrapHook>>>
>;
export type GetBootstrapQueryError = unknown;

/**
 * @summary Get app bootstrap data
 */
export const useGetBootstrap = <
  TData = Awaited<ReturnType<ReturnType<typeof useGetBootstrapHook>>>,
  TError = unknown,
>(
  params?: GetBootstrapParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<ReturnType<typeof useGetBootstrapHook>>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<ReturnType<typeof useCustomInstance>>;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = useGetBootstrapQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * @summary Get health check status
 */
export const useGetHealthCheckHook = () => {
  const getHealthCheck = useCustomInstance<string>();

  return (
    options?: SecondParameter<ReturnType<typeof useCustomInstance>>,
    signal?: AbortSignal
  ) => {
    return getHealthCheck(
      { method: 'get', signal, url: `/api/health-check` },
      options
    );
  };
};

export const getGetHealthCheckQueryKey = () => {
  return [`/api/health-check`] as const;
};

export const useGetHealthCheckInfiniteQueryOptions = <
  TData = InfiniteData<
    Awaited<ReturnType<ReturnType<typeof useGetHealthCheckHook>>>
  >,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseInfiniteQueryOptions<
      Awaited<ReturnType<ReturnType<typeof useGetHealthCheckHook>>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<ReturnType<typeof useCustomInstance>>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetHealthCheckQueryKey();

  const getHealthCheck = useGetHealthCheckHook();

  const queryFn: QueryFunction<
    Awaited<ReturnType<ReturnType<typeof useGetHealthCheckHook>>>
  > = ({ signal }) => getHealthCheck(requestOptions, signal);

  return {
    cacheTime: 0,
    queryFn,
    queryKey,
    refetchOnWindowFocus: false,
    ...queryOptions,
  } as UseInfiniteQueryOptions<
    Awaited<ReturnType<ReturnType<typeof useGetHealthCheckHook>>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetHealthCheckInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof useGetHealthCheckHook>>>
>;
export type GetHealthCheckInfiniteQueryError = unknown;

/**
 * @summary Get health check status
 */
export const useGetHealthCheckInfinite = <
  TData = InfiniteData<
    Awaited<ReturnType<ReturnType<typeof useGetHealthCheckHook>>>
  >,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseInfiniteQueryOptions<
      Awaited<ReturnType<ReturnType<typeof useGetHealthCheckHook>>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<ReturnType<typeof useCustomInstance>>;
}): UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = useGetHealthCheckInfiniteQueryOptions(options);

  const query = useInfiniteQuery(queryOptions) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const useGetHealthCheckQueryOptions = <
  TData = Awaited<ReturnType<ReturnType<typeof useGetHealthCheckHook>>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<ReturnType<typeof useGetHealthCheckHook>>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<ReturnType<typeof useCustomInstance>>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetHealthCheckQueryKey();

  const getHealthCheck = useGetHealthCheckHook();

  const queryFn: QueryFunction<
    Awaited<ReturnType<ReturnType<typeof useGetHealthCheckHook>>>
  > = ({ signal }) => getHealthCheck(requestOptions, signal);

  return {
    cacheTime: 0,
    queryFn,
    queryKey,
    refetchOnWindowFocus: false,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<ReturnType<typeof useGetHealthCheckHook>>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetHealthCheckQueryResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof useGetHealthCheckHook>>>
>;
export type GetHealthCheckQueryError = unknown;

/**
 * @summary Get health check status
 */
export const useGetHealthCheck = <
  TData = Awaited<ReturnType<ReturnType<typeof useGetHealthCheckHook>>>,
  TError = unknown,
>(options?: {
  query?: Partial<
    UseQueryOptions<
      Awaited<ReturnType<ReturnType<typeof useGetHealthCheckHook>>>,
      TError,
      TData
    >
  >;
  request?: SecondParameter<ReturnType<typeof useCustomInstance>>;
}): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = useGetHealthCheckQueryOptions(options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

/**
 * @summary Get user stories
 */
export const useGetStoriesHook = () => {
  const getStories = useCustomInstance<Stories>();

  return (
    params?: GetStoriesParams,
    options?: SecondParameter<ReturnType<typeof useCustomInstance>>,
    signal?: AbortSignal
  ) => {
    return getStories(
      { method: 'get', params, signal, url: `/api/stories` },
      options
    );
  };
};

export const getGetStoriesQueryKey = (params?: GetStoriesParams) => {
  return [`/api/stories`, ...(params ? [params] : [])] as const;
};

export const useGetStoriesInfiniteQueryOptions = <
  TData = InfiniteData<
    Awaited<ReturnType<ReturnType<typeof useGetStoriesHook>>>,
    GetStoriesParams['skip']
  >,
  TError = unknown,
>(
  params?: GetStoriesParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<ReturnType<typeof useGetStoriesHook>>>,
        TError,
        TData,
        Awaited<ReturnType<ReturnType<typeof useGetStoriesHook>>>,
        QueryKey,
        GetStoriesParams['skip']
      >
    >;
    request?: SecondParameter<ReturnType<typeof useCustomInstance>>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetStoriesQueryKey(params);

  const getStories = useGetStoriesHook();

  const queryFn: QueryFunction<
    Awaited<ReturnType<ReturnType<typeof useGetStoriesHook>>>,
    QueryKey,
    GetStoriesParams['skip']
  > = ({ signal, pageParam }) =>
    getStories({ skip: pageParam, ...params }, requestOptions, signal);

  return {
    cacheTime: 0,
    queryFn,
    queryKey,
    refetchOnWindowFocus: false,
    ...queryOptions,
  } as UseInfiniteQueryOptions<
    Awaited<ReturnType<ReturnType<typeof useGetStoriesHook>>>,
    TError,
    TData,
    Awaited<ReturnType<ReturnType<typeof useGetStoriesHook>>>,
    QueryKey,
    GetStoriesParams['skip']
  > & { queryKey: QueryKey };
};

export type GetStoriesInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof useGetStoriesHook>>>
>;
export type GetStoriesInfiniteQueryError = unknown;

/**
 * @summary Get user stories
 */
export const useGetStoriesInfinite = <
  TData = InfiniteData<
    Awaited<ReturnType<ReturnType<typeof useGetStoriesHook>>>,
    GetStoriesParams['skip']
  >,
  TError = unknown,
>(
  params?: GetStoriesParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<ReturnType<typeof useGetStoriesHook>>>,
        TError,
        TData,
        Awaited<ReturnType<ReturnType<typeof useGetStoriesHook>>>,
        QueryKey,
        GetStoriesParams['skip']
      >
    >;
    request?: SecondParameter<ReturnType<typeof useCustomInstance>>;
  }
): UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = useGetStoriesInfiniteQueryOptions(params, options);

  const query = useInfiniteQuery(queryOptions) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const useGetStoriesQueryOptions = <
  TData = Awaited<ReturnType<ReturnType<typeof useGetStoriesHook>>>,
  TError = unknown,
>(
  params?: GetStoriesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<ReturnType<typeof useGetStoriesHook>>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<ReturnType<typeof useCustomInstance>>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetStoriesQueryKey(params);

  const getStories = useGetStoriesHook();

  const queryFn: QueryFunction<
    Awaited<ReturnType<ReturnType<typeof useGetStoriesHook>>>
  > = ({ signal }) => getStories(params, requestOptions, signal);

  return {
    cacheTime: 0,
    queryFn,
    queryKey,
    refetchOnWindowFocus: false,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<ReturnType<typeof useGetStoriesHook>>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetStoriesQueryResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof useGetStoriesHook>>>
>;
export type GetStoriesQueryError = unknown;

/**
 * @summary Get user stories
 */
export const useGetStories = <
  TData = Awaited<ReturnType<ReturnType<typeof useGetStoriesHook>>>,
  TError = unknown,
>(
  params?: GetStoriesParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<ReturnType<typeof useGetStoriesHook>>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<ReturnType<typeof useCustomInstance>>;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = useGetStoriesQueryOptions(params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const useCreateStoryControllerCreateStoryHook = () => {
  const createStoryControllerCreateStory = useCustomInstance<void>();

  return (options?: SecondParameter<ReturnType<typeof useCustomInstance>>) => {
    return createStoryControllerCreateStory(
      { method: 'post', url: `/api/stories` },
      options
    );
  };
};

export const useCreateStoryControllerCreateStoryMutationOptions = <
  TError = unknown,
  TVariables = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<
      ReturnType<ReturnType<typeof useCreateStoryControllerCreateStoryHook>>
    >,
    TError,
    TVariables,
    TContext
  >;
  request?: SecondParameter<ReturnType<typeof useCustomInstance>>;
}): UseMutationOptions<
  Awaited<
    ReturnType<ReturnType<typeof useCreateStoryControllerCreateStoryHook>>
  >,
  TError,
  TVariables,
  TContext
> => {
  const { mutation: mutationOptions, request: requestOptions } = options ?? {};

  const createStoryControllerCreateStory =
    useCreateStoryControllerCreateStoryHook();

  const mutationFn: MutationFunction<
    Awaited<
      ReturnType<ReturnType<typeof useCreateStoryControllerCreateStoryHook>>
    >,
    TVariables
  > = () => {
    return createStoryControllerCreateStory(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CreateStoryControllerCreateStoryMutationResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof useCreateStoryControllerCreateStoryHook>>
  >
>;

export type CreateStoryControllerCreateStoryMutationError = unknown;

export const useCreateStoryControllerCreateStory = <
  TError = unknown,
  TVariables = void,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<
      ReturnType<ReturnType<typeof useCreateStoryControllerCreateStoryHook>>
    >,
    TError,
    TVariables,
    TContext
  >;
  request?: SecondParameter<ReturnType<typeof useCustomInstance>>;
}) => {
  const mutationOptions =
    useCreateStoryControllerCreateStoryMutationOptions(options);

  return useMutation(mutationOptions);
};

/**
 * @summary Get user story
 */
export const useGetStoryHook = () => {
  const getStory = useCustomInstance<Story>();

  return (
    id: string,
    params?: GetStoryParams,
    options?: SecondParameter<ReturnType<typeof useCustomInstance>>,
    signal?: AbortSignal
  ) => {
    return getStory(
      { method: 'get', params, signal, url: `/api/stories/${id}` },
      options
    );
  };
};

export const getGetStoryQueryKey = (id: string, params?: GetStoryParams) => {
  return [`/api/stories/${id}`, ...(params ? [params] : [])] as const;
};

export const useGetStoryInfiniteQueryOptions = <
  TData = InfiniteData<
    Awaited<ReturnType<ReturnType<typeof useGetStoryHook>>>,
    GetStoryParams['skip']
  >,
  TError = unknown,
>(
  id: string,
  params?: GetStoryParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<ReturnType<typeof useGetStoryHook>>>,
        TError,
        TData,
        Awaited<ReturnType<ReturnType<typeof useGetStoryHook>>>,
        QueryKey,
        GetStoryParams['skip']
      >
    >;
    request?: SecondParameter<ReturnType<typeof useCustomInstance>>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetStoryQueryKey(id, params);

  const getStory = useGetStoryHook();

  const queryFn: QueryFunction<
    Awaited<ReturnType<ReturnType<typeof useGetStoryHook>>>,
    QueryKey,
    GetStoryParams['skip']
  > = ({ signal, pageParam }) =>
    getStory(id, { skip: pageParam, ...params }, requestOptions, signal);

  return {
    cacheTime: 0,
    enabled: !!id,
    queryFn,
    queryKey,
    refetchOnWindowFocus: false,
    ...queryOptions,
  } as UseInfiniteQueryOptions<
    Awaited<ReturnType<ReturnType<typeof useGetStoryHook>>>,
    TError,
    TData,
    Awaited<ReturnType<ReturnType<typeof useGetStoryHook>>>,
    QueryKey,
    GetStoryParams['skip']
  > & { queryKey: QueryKey };
};

export type GetStoryInfiniteQueryResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof useGetStoryHook>>>
>;
export type GetStoryInfiniteQueryError = unknown;

/**
 * @summary Get user story
 */
export const useGetStoryInfinite = <
  TData = InfiniteData<
    Awaited<ReturnType<ReturnType<typeof useGetStoryHook>>>,
    GetStoryParams['skip']
  >,
  TError = unknown,
>(
  id: string,
  params?: GetStoryParams,
  options?: {
    query?: Partial<
      UseInfiniteQueryOptions<
        Awaited<ReturnType<ReturnType<typeof useGetStoryHook>>>,
        TError,
        TData,
        Awaited<ReturnType<ReturnType<typeof useGetStoryHook>>>,
        QueryKey,
        GetStoryParams['skip']
      >
    >;
    request?: SecondParameter<ReturnType<typeof useCustomInstance>>;
  }
): UseInfiniteQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = useGetStoryInfiniteQueryOptions(id, params, options);

  const query = useInfiniteQuery(queryOptions) as UseInfiniteQueryResult<
    TData,
    TError
  > & { queryKey: QueryKey };

  query.queryKey = queryOptions.queryKey;

  return query;
};

export const useGetStoryQueryOptions = <
  TData = Awaited<ReturnType<ReturnType<typeof useGetStoryHook>>>,
  TError = unknown,
>(
  id: string,
  params?: GetStoryParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<ReturnType<typeof useGetStoryHook>>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<ReturnType<typeof useCustomInstance>>;
  }
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getGetStoryQueryKey(id, params);

  const getStory = useGetStoryHook();

  const queryFn: QueryFunction<
    Awaited<ReturnType<ReturnType<typeof useGetStoryHook>>>
  > = ({ signal }) => getStory(id, params, requestOptions, signal);

  return {
    cacheTime: 0,
    enabled: !!id,
    queryFn,
    queryKey,
    refetchOnWindowFocus: false,
    ...queryOptions,
  } as UseQueryOptions<
    Awaited<ReturnType<ReturnType<typeof useGetStoryHook>>>,
    TError,
    TData
  > & { queryKey: QueryKey };
};

export type GetStoryQueryResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof useGetStoryHook>>>
>;
export type GetStoryQueryError = unknown;

/**
 * @summary Get user story
 */
export const useGetStory = <
  TData = Awaited<ReturnType<ReturnType<typeof useGetStoryHook>>>,
  TError = unknown,
>(
  id: string,
  params?: GetStoryParams,
  options?: {
    query?: Partial<
      UseQueryOptions<
        Awaited<ReturnType<ReturnType<typeof useGetStoryHook>>>,
        TError,
        TData
      >
    >;
    request?: SecondParameter<ReturnType<typeof useCustomInstance>>;
  }
): UseQueryResult<TData, TError> & { queryKey: QueryKey } => {
  const queryOptions = useGetStoryQueryOptions(id, params, options);

  const query = useQuery(queryOptions) as UseQueryResult<TData, TError> & {
    queryKey: QueryKey;
  };

  query.queryKey = queryOptions.queryKey;

  return query;
};
