/* eslint-disable no-redeclare */
// @ts-nocheck

/**
 * Generated by orval v6.20.0 🍺
 * Do not edit manually.
 * Fabled API
 * Fabled API Documentation
 * OpenAPI spec version: 1.0
 */
export type GetStoryParams = {
  image?: ImageTransformationQuery;
};

export type GetStoriesStatus =
  (typeof GetStoriesStatus)[keyof typeof GetStoriesStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetStoriesStatus = {
  failed: 'failed',
  inprogress: 'inprogress',
  success: 'success',
} as const;

export type GetStoriesParams = {
  skip?: number;
  take?: number;
  status?: GetStoriesStatus;
  image?: ImageTransformationQuery;
};

export type GetBootstrapParams = {
  image?: ImageTransformationQuery;
};

export interface CreateInquiryRequest {
  email: string;
  message: string;
  subject: string;
}

export interface Story {
  content: string;
  id: string;
  image: string;
  readTime: number;
  title: string;
}

export type HttpExceptionResponseMessage = string | string[];

export interface HttpExceptionResponse {
  error: string;
  message: HttpExceptionResponseMessage;
  statusCode: number;
}

export interface CreateStoryResponse {
  id: string;
}

export interface CreateStoryRequest {
  characterId: string;
  moralLessonId: string;
  placeOfEventId: string;
  promptId: string;
  readTime: number;
}

export interface StoryItem {
  id: string;
  image: string;
  readTime: number;
  title: string;
}

export interface Stories {
  data: StoryItem[];
  total: number;
}

export interface Config {
  privacyPolicyUrl: string;
  termsAndConditionsUrl: string;
}

export interface PromptItem {
  id: string;
  message: string;
}

export interface PlaceOfEventItem {
  id: string;
  image: string;
  title: string;
}

export interface CharacterItem {
  id: string;
  image: string;
  title: string;
}

export interface MoralLessonsItem {
  description: string;
  id: string;
  title: string;
}

export interface Bootstrap {
  characters: CharacterItem[];
  config: Config;
  moralLessons: MoralLessonsItem[];
  placeOfEvents: PlaceOfEventItem[];
  prompts: PromptItem[];
}

export type ImageTransformationQueryCrop =
  (typeof ImageTransformationQueryCrop)[keyof typeof ImageTransformationQueryCrop];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ImageTransformationQueryCrop = {
  crop: 'crop',
  fill: 'fill',
  fit: 'fit',
  imagga_crop: 'imagga_crop',
  imagga_scale: 'imagga_scale',
  lfill: 'lfill',
  limit: 'limit',
  lpad: 'lpad',
  mfit: 'mfit',
  mpad: 'mpad',
  pad: 'pad',
  scale: 'scale',
  thumb: 'thumb',
} as const;

export type ImageTransformationQueryAspectRatio =
  (typeof ImageTransformationQueryAspectRatio)[keyof typeof ImageTransformationQueryAspectRatio];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ImageTransformationQueryAspectRatio = {
  '16:9': '16:9',
  '1:1': '1:1',
  '3:1': '3:1',
  '3:2': '3:2',
  '4:3': '4:3',
  '5:4': '5:4',
} as const;

export interface ImageTransformationQuery {
  aspectRatio?: ImageTransformationQueryAspectRatio;
  crop?: ImageTransformationQueryCrop;
  height?: number;
  width?: number;
}
