name: Distribute iOS

on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment

jobs:
  ios:
    name: Build and Push
    runs-on: macos-14
    environment: ${{ github.event.inputs.environment }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn

      - name: Setup CocoaPods
        uses: maxim-lobanov/setup-cocoapods@v1
        with:
          version: 1.15.2

      - name: Read app version
        id: version
        uses: beaconbrigade/package-json-version@v0.3.2

      - name: Print app version
        run: echo "The version was ${{ steps.version.outputs.version }}"

      - name: Install dependencies
        run: yarn

      - name: Build application
        run: yarn build
        env:
          VITE_API_ENDPOINT: ${{ vars.VITE_API_ENDPOINT }}
          VITE_API_SUBSCRIPTION: ${{ vars.VITE_API_SUBSCRIPTION }}
          VITE_FIREBASE_API_KEY: ${{ vars.VITE_FIREBASE_API_KEY }}
          VITE_FIREBASE_APP_ID: ${{ vars.VITE_FIREBASE_APP_ID }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ vars.VITE_FIREBASE_AUTH_DOMAIN }}
          VITE_FIREBASE_MEASUREMENT_ID: ${{ vars.VITE_FIREBASE_MEASUREMENT_ID }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ vars.VITE_FIREBASE_MESSAGING_SENDER_ID }}
          VITE_FIREBASE_PROJECT_ID: ${{ vars.VITE_FIREBASE_PROJECT_ID }}
          VITE_FIREBASE_STORAGE_BUCKET=: ${{ vars.VITE_FIREBASE_STORAGE_BUCKET }}

      - name: Capacitor sync
        run: npx cap sync

      - name: Bump build number
        uses: ults-io/mobile-version-bump-action@v2
        with:
          build-number: ${{github.run_number}}
          app-version: ${{ steps.version.outputs.version }}
          ios-project-path: ./ios/App

      - name: Install the Apple certificate and provisioning profile
        env:
          BUILD_CERTIFICATE_BASE64: ${{ secrets.IOS_PROD_CERTIFICATE }}
          P12_PASSWORD: ${{ secrets.IOS_PROD_CERTIFICATE_PASSWORD }}
          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.IOS_PROVISION_PRODUCTION }}
          KEYCHAIN_PASSWORD: ${{ secrets.IOS_KEYCHAIN_PASSWORD }}
        run: |
          # create variables
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          # import certificate and provisioning profile from secrets
          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode -o $PP_PATH

          # create temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

          # apply provisioning profile
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles

      - name: Pod install
        run: pod install --project-directory=${{ github.workspace }}/ios/App

      - name: Build Release
        run: |
          xcodebuild -quiet -workspace ${{ github.workspace }}/ios/App/App.xcworkspace -scheme "App" clean archive -archivePath "Actions" -configuration "Release"
          ls ${{ github.workspace }}

      - name: Export .ipa
        env:
          EXPORT_PLIST: ${{ secrets.IOS_EXPORT_PRODUCTION }}
        run: |
          EXPORT_PLIST_PATH=$RUNNER_TEMP/ExportOptions.plist
          echo -n "$EXPORT_PLIST" | base64 --decode -o $EXPORT_PLIST_PATH
          xcodebuild -exportArchive \
            -archivePath ${{ github.workspace }}/Actions.xcarchive \
            -exportOptionsPlist $EXPORT_PLIST_PATH \
            -exportPath $RUNNER_TEMP/export
          ls $RUNNER_TEMP/export

      - name: Decode auth API Key file and save it
        env:
          API_KEY_BASE64: ${{ secrets.APPSTORE_API_PRIVATE_KEY }}
        run: |
          mkdir -p ~/private_keys
          echo -n "$API_KEY_BASE64" | base64 --decode -o ~/private_keys/AuthKey_${{ secrets.APPSTORE_API_KEY_ID }}.p8
          ls ~/private_keys

      - name: Push to TestFlight
        run: |
          xcrun altool --validate-app -f $RUNNER_TEMP/export/App.ipa -t ios --apiKey ${{ secrets.APPSTORE_API_KEY_ID }} --apiIssuer ${{ secrets.APPSTORE_ISSUER_ID }}
          xcrun altool --upload-app -f $RUNNER_TEMP/export/App.ipa -t ios --apiKey ${{ secrets.APPSTORE_API_KEY_ID }} --apiIssuer ${{ secrets.APPSTORE_ISSUER_ID }}
